name: "Build and populate cache"
on:
  pull_request:
  push:
  schedule:
    # everyday at 2:51
    - cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - drewrisinger
        cachixName:
          - drewrisinger
        nixPath:
          - nixpkgs=channel:nixos-20.03
          - nixpkgs=channel:nixpkgs-unstable
          - nixpkgs=channel:nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: "${{ matrix.nixPath }}"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build nix packages
      run: NIXPKGS_ALLOW_UNFREE=1 nix run nixpkgs.nix-build-uncached -c nix-build-uncached non-broken.nix
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}"
